export const link = [
    {
        id:1,
        name:"Home",
        path:"/"
    },
    {
        id:2,
        name:"Men",
        path:"/men"
    },
    {
        id:3,
        name:"Women",
        path:"/women"
    },
    {
        id:4,
        name:"Kids",
        path:"/kids"
    },
    {
        id:5,
        name:"Sports",
        path:"/sports"
    },
    {
        id:6,
        name:"Outlet",
        path:"/outlet"
    }
]